image: seleniarm/selenium:latest  # Образ, що включає Chrome та ChromeDriver

stages:
  - test

test-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover
