image: python:3.11

before_script:
  - apt-get update && apt-get install -y python3-distutils

stages:
  - test

test_job:
  stage: test
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python -m unittest discover
