stages:
  - test

test:
  stage: test
  script:
    - echo "Installing dependencies..."
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python -m unittest discover -s tests -p '*_test.py'
