image: python:3.11

before_script:
  - apt-get update && apt-get install -y python3-distutils

stages:
  - test

test:
  stage: test
  image: python:3.11
  script:
    - apt-get update && apt-get install -y python3-distutils
    - echo "Installing dependencies..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python -m unittest discover -s tests
