image: python:3.12

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y python3-distutils
  script:
    - echo "Встановлюємо залежності..."
    - pip install -r requirements.txt
