image: selenium/standalone-chrome:latest

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Встановлюємо залежності
    - python -m unittest discover -s tests -p '*_test.py'
