image: selenium/standalone-chrome:latest

stages:
  - test

test:
  stage: test
  script:
    - echo "Installing dependencies..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running tests..."
    - python -m unittest discover -s tests
