stages:
  - test

test:
  image: selenium/standalone-chrome:latest
  stage: test
  services:
    - name: selenium/standalone-chrome:latest
      alias: chrome
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests
