image: debian:bookworm

before_script:
  - echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free" > /etc/apt/sources.list
  - echo "deb http://deb.debian.org/debian-security/ bookworm-security main contrib non-free" >> /etc/apt/sources.list
  - echo "deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list
  - apt-get update && apt-get install -y python3 python3-pip wget gnupg2 unzip chromium chromium-driver libnss3 libgconf-2-4 libxi6 libxrender1 libxrandr2 libgtk-3-0 libxss1 fonts-liberation libappindicator3-1 libasound2

stages:
  - test

test:
  stage: test
  script:
    - echo "Installing dependencies..."
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - echo "Running tests..."
    - python3 -m unittest discover -s tests
